[features]
seeds = false
skip-lint = false

[programs.mainnet]
safe_presale = "Cbq8bFSvGDjxmqEfPcxaujgfW1ZgggzYgDwcQRNY4jr"

[programs.localnet]
safe_presale = "Cbq8bFSvGDjxmqEfPcxaujgfW1ZgggzYgDwcQRNY4jr"

[programs.devnet]
safe_presale = "Cbq8bFSvGDjxmqEfPcxaujgfW1ZgggzYgDwcQRNY4jr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"