[features]
seeds = false
skip-lint = false

[programs.mainnet]
safe_presale = "8caweP2SL16aUW55my9muRgp5xvfQh2qepYNtB3SFDjx"

[programs.localnet]
safe_presale = "8caweP2SL16aUW55my9muRgp5xvfQh2qepYNtB3SFDjx"

[programs.devnet]
safe_presale = "8caweP2SL16aUW55my9muRgp5xvfQh2qepYNtB3SFDjx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"