[features]
seeds = false
skip-lint = false

[programs.mainnet]
safe_presale = "6DvsdPa3nXFjFG8ENuABoWeRjQaHUks2pKKqGD9ihekw"

[programs.localnet]
safe_presale = "6DvsdPa3nXFjFG8ENuABoWeRjQaHUks2pKKqGD9ihekw"

[programs.devnet]
safe_presale = "6DvsdPa3nXFjFG8ENuABoWeRjQaHUks2pKKqGD9ihekw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/junyang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"